### ISSUE TITLE
Modal Close Button Functionality Issue

### ISSUE THREAD

**Issue by gaurav-singh-b** [Rakeshkumawat1/mui-react-modal#15] opened 2023-07-20 06:47 UTC
I noticed a functionality issue with the modal's cancel button. Currently, when I click outside the modal, the cancel button's action is triggered as well. This behavior is unexpected and may lead to accidental cancellation of actions. The cancel button should only be activated when explicitly clicked, and clicking outside the modal should not trigger any action. Please investigate and resolve this issue to improve the user experience and prevent accidental data loss or unintended actions

**Comment by BAHADURPRATAP** [comment] 2023-07-20 12:05
Thank you for bringing this issue to our attention! We appreciate your feedback and are actively looking into it. We will investigate the problem further to identify the root cause and work on a resolution.

Best regards,
[mui-react-modal  ,Team]

**Comment by Rakeshkumawat1** [comment] 2023-07-31 14:51
Closing this issue as fixed in pr #20 .

**Closed as completed by Rakeshkumawat1** 2023-07-31 14:51 UTC
